apiVersion: v1
kind: Service
metadata:
  name: kbtvuelo-service
  namespace: default
  annotations:
    argocd.argoproj.io/tracking-id: kbtvuelo:/Service:default/kbtvuelo-service
spec:
  type: NodePort
  selector:
    app: kbtvuelo
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089  # Puedes cambiarlo si ya está ocupado
      protocol: TCP
